//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBFSManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\utorrent</string>
  <string>W:\utorrent</string>
  <string>Q:\utorrent</string>
  <string>V:\utorrent</string>
  <string>X:\utorrent</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FileFolderPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FileFolderPaths"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C=System</string>
  <string>X=DownloadedWBFS</string>
  <string>Q=WiiWBFSDrive</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FriendlyDeviceNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FriendlyDeviceNames"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnOrdering_Device_0x00000000 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnOrdering_Device_0x00000000"]));
            }
            set {
                this["ColumnOrdering_Device_0x00000000"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnVisibility_Device_0x00000000 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnVisibility_Device_0x00000000"]));
            }
            set {
                this["ColumnVisibility_Device_0x00000000"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnOrdering_Device_0x00000001 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnOrdering_Device_0x00000001"]));
            }
            set {
                this["ColumnOrdering_Device_0x00000001"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnVisibility_Device_0x00000001 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnVisibility_Device_0x00000001"]));
            }
            set {
                this["ColumnVisibility_Device_0x00000001"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnOrdering_Device_0x00000002 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnOrdering_Device_0x00000002"]));
            }
            set {
                this["ColumnOrdering_Device_0x00000002"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnVisibility_Device_0x00000002 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnVisibility_Device_0x00000002"]));
            }
            set {
                this["ColumnVisibility_Device_0x00000002"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnOrdering_Device_0x00000004 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnOrdering_Device_0x00000004"]));
            }
            set {
                this["ColumnOrdering_Device_0x00000004"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnVisibility_Device_0x00000004 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnVisibility_Device_0x00000004"]));
            }
            set {
                this["ColumnVisibility_Device_0x00000004"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnOrdering_Device_0x00000008 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnOrdering_Device_0x00000008"]));
            }
            set {
                this["ColumnOrdering_Device_0x00000008"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnVisibility_Device_0x00000008 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnVisibility_Device_0x00000008"]));
            }
            set {
                this["ColumnVisibility_Device_0x00000008"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnOrdering_Device_0x00000010 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnOrdering_Device_0x00000010"]));
            }
            set {
                this["ColumnOrdering_Device_0x00000010"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnVisibility_Device_0x00000010 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnVisibility_Device_0x00000010"]));
            }
            set {
                this["ColumnVisibility_Device_0x00000010"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnOrdering_Device_0x00000020 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnOrdering_Device_0x00000020"]));
            }
            set {
                this["ColumnOrdering_Device_0x00000020"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColumnVisibility_Device_0x00000020 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColumnVisibility_Device_0x00000020"]));
            }
            set {
                this["ColumnVisibility_Device_0x00000020"] = value;
            }
        }
    }
}
